@startuml 

class Mascota
class Alimento 
class Carne
class Juguete
class Pelota
class Carro
class Stamina
class Jabon
class Agua
class Lampara
class Dia 
class Noche 
class Puntuacion
class Moneda 
class Tristeza
class Felicidad
class Desagrado
class Emocion 
class Foco 
class Sueño 
class Baño

package Mascota{

}
Alimento "*" --o "1" Mascota
Mascota "1" o-- "3" Juguete
Carne "1" --|> "1.." Alimento
Pelota "1" --|> "1" Juguete
Lampara "1" --* "1" Foco

Felicidad "1" --|> "*" Emocion 
Tristeza "1" --|> "*" Emocion
Desagrado "1" --|> "*" Emocion
Mascota "1" *-- "*" Emocion 

Mascota "1" *-- "1" Sueño 

Sueño "1" --|> "1" Noche 
Noche "1" o-- "1" Lampara 
Puntuacion "1" --|> "1.." Moneda 
Juguete "1" --|> "*" Felicidad
Dia "1" --* "1" Juguete

Jabon "1" --o "1" Agua 
Carro "1" *-- "*" Puntuacion

Mascota "1" o-- "1" Carro
Sueño "1" --|> "1" Stamina
Baño "1" *-- "1" Agua

Stamina "1" *-- "1" Baño




@endluml